### ISSUE TITLE
VCS compilation failure doesn't seem to be reported

### ISSUE THREAD

**Issue by THofstee** [leonardt/fault#126]
I'm running `tester.compile(...)` but if I look at the modification time of the simv generated with the VCS backend it's not being modified.

**Comment by THofstee** [comment]
Ok, it looks like VCS compilation actually is _failing_ but fault doesn't report any errors.

**Comment by leonardt** [comment]
Can you provide a way to reproduce the issue?

**Comment by THofstee** [comment]
I think this might be related to `tester.compile` not being implemented for the SystemVerilog target mentioned in the other issue?
