### ISSUE TITLE
SymbolicTester doesn't work with latest CoSA

### ISSUE THREAD

**Issue by benreynwar** [leonardt/fault#129]
Currently running tests/test_symbolic_tester.py fails with

    CoSA: error: ambiguous option: --solver could match --solver-name, --solver-options

The automated tests are skipping this test due to msat not be present on the test machine.

**Comment by leonardt** [comment]
Thanks for creating the issue, I will investigate and fix this, should be simple (assuming cosa just updated the name of the CLI option to --solver-name)
