### ISSUE TITLE
Add a way to run a tester on multiple circuit implementations w the same interface

### ISSUE THREAD

**Issue by rsetaluri** [leonardt/fault#16]
Often we want to run a tester on multiple implementations of the "same circuit". For example if we have magma circuits, `foo_impl1` and `foo_impl2` where `foo_impl1.interface == foo_impl2.interface`, we want to create a tester, build test vectors and then run the tests against each implementation. Right now we might do `tester = fault.Tester(foo_impl1)` and then change the circuit later (i.e. `tester.circuit = foo_impl2`) to test the other implementation.

We should build a mechanism where we pass in an interface and then can run the tests against any circuit of that interface.

**Comment by leonardt** [comment]
One option is to separate the notion of test vector generation and running tests. Right now the tester is responsible for both of these. We could pass an interface to a test vector constructor, then have a tester that can rum a test with the test vectors for any circuit that satisfies the interface.

For documentation, here is an example of where this would be used (which currently uses the `tester.circuit` hack): https://github.com/rsetaluri/magma_cgra/blob/master/test_cb/test_cb_regression.py#L115-L118
