### ISSUE TITLE
Move verilator test infra from magma to fault

### ISSUE THREAD

**Issue by rsetaluri** [leonardt/fault#2]
magma/magma/testing/verilator.py should be in fault, IMO.

**Comment by leonardt** [comment]
Yup, this is WIP in my changes to refactor the magma_cgra tests to abstract out the compile and run for verilator. The interface should be specifying the target/backend to the Tester, then it should handle all the code for that specific simulator.

**Comment by leonardt** [comment]
If we merge in #7 this will be resolved. Any other comments on that PR? I'm going to spend some time documenting and cleaning up the code base at this point before new features are added. Will submit a PR with that.

**Comment by leonardt** [comment]
Done!
