### ISSUE TITLE
Confusing semantics of step function in fault.

### ISSUE THREAD

**Issue by rdaly525** [leonardt/fault#49]
Consider the simple program 

```
tester.step()
tester.print(sig)
tester.step()

```

This will output the following code:

```
top->eval();
top->clk ^=1;
printf(top->sig);
top->eval();
top->clk ^= 1;
```

I would make an argument that this is confusing semantics as calling step() does not actually evaluate the clock change. The code I wrote, I would have have expected to get the value of sig after the first clock tick, but instead I am getting the value before the first clock tick.

This would simply be fixed by changing step() to mean:

```
top->clk ^=1;
top->eval()
```

In general, programs should be written in the following style to match hardware semantics.

```
for () {
  //Assume posedge clk just occurred meaning clk=1
  //Set inputs
  // eval
  // clk = 0
  // eval
  // read all outputs
  // clk = 1
  // eval

**Comment by rsetaluri** [comment]
I agree, that makes sense. I think there was some arcane reason I did this, though I don't remember anymore. We can make this change.

**Comment by phanrahan** [comment]
I assume we still need to call eval?

Also, what about reset? And for a clocked circuits with register outputs, can you call expect
right away?
