### ISSUE TITLE
Define the semantics of tester.poke,eval,expect,step

### ISSUE THREAD

**Issue by rsetaluri** [leonardt/fault#8]
There seems to be some ambiguity in these commands. These should be well defined. Of course, their associated code is well defined but we should consider their semantics.

**Comment by leonardt** [comment]
What we decided today: `expect` semantics should be that the expectation of the result after `eval` is called. Currently it is the expectation of the result *when* the next `eval` is called.

**Comment by leonardt** [comment]
Unresolved issue is whether we need to call `eval` at all. One option is to have an `eval` implicit on every `poke`, and then do analysis to reason about when `eval` actually needs to be called (for optimization purposes).

We could provide two modes. One simple mode where `eval` is called on every poke, and an optimized mode where the user can control when `eval` occurs.

**Comment by leonardt** [comment]
I think this is cleared up with the new Action pattern.

Before we close this issue, I think it would be good to write up some documentation on this.

**Comment by rsetaluri** [comment]
It would be good to do so. However we define it should be agnostic of the target simulator, and our targets should always properly map our semantics to the target's semantics.

**Comment by phanrahan** [comment]
Are these functions documented? I couldn't find them.

**Comment by rsetaluri** [comment]
They are not yet documented. I can work on this. I think the most useful documentation is how they map to the backend simulators.

As a rough guideline, for verilator:
-- `poke(x, value)` --> `set_x(value)`
-- `expect(x, value)` --> `assert(get_x() == value)`
-- `eval()` --> `eval()`
-- `step(n)` -->
```
for i = 1 : n
    set_clk(~get_clk())
    eval()
```

**Comment by leonardt** [comment]
Actions are now documented at https://github.com/leonardt/fault/blob/master/doc/actions.md, will open a separate issue for documenting `Tester`.
